config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # Generic syntax:
  # verb 'path', to: 'controller#action'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
    @members = ['Jeremaia', 'dimitri', 'germain', 'damien', 'julien']
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <h1>The Spoon</h1> <!-- Add this -->
    <%= yield %>
        <p>A very simple footer</p>  <!-- Add this -->

  </body>
</html>

app/views/pages/about.html.erb
<h1>Our first view 🚀</h1>

<p>Now is <%= Time.now %><p>
<%= link_to "Know more about us", about_path %>
<%= link_to "Meet our team", contact_path %>

app/views/pages/contact.html.erb
<h2>Meet our team</h2>
<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

<%= link_to "Know more about us", about_path %>
<%= link_to "Meet our team", contact_path %>